version: "3.9"
services:

  viajamas:
    image: viajamas
    container_name: viajamas-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-network
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: 8462
      MYSQL_DATABASE: bdviajamas
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - spring-network
    volumes:
      - mysql-volume:/var/lib/mysql
networks:
  spring-network:
volumes:
  mysql-volume: